name: Running tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests for gloop

    steps:
    - uses: actions/checkout@v3
    - name: Set up python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Install poetry
      run: |
        curl -sSL \
          "https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py" | python
        # Adding `poetry` to `$PATH`:
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    
    - name: Install dependency
      run: |
        poetry config virtualenvs.in-project true
        poetry run pip install -U pip
        poetry install
    
    - name: Run tests
      run: |
        make test
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
